name: Terraform Format and Plan

permissions:
  contents: read 
  pull-requests: write
  actions: read

on:
  pull_request:
    paths:
      - '**/*.tf'

  push:
    branches:
      - main

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    name: Run terraform fmt and terraform plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Run terraform fmt
        run: terraform fmt -check -diff

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

  terraform-apply:
    runs-on: ubuntu-latest
    name: Apply Terraform changes if merged into main
    needs: terraform-fmt
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  # # Security Checks (IaC and Secrets Scanning)
  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Check for IaC misconfigurations with Checkov
  #       run: |
  #         pip install checkov
  #         checkov -d . --skip-check CKV_AWS_17